
on:
  push:
    branches:
      - master

jobs:

  test:

    runs-on: ubuntu-16.04
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        
      - name: Download dependencies
        run: npm i --prefix remote-frontend/
        
      - name: Run tests  
        run: npm test --prefix remote-frontend/
        
      - name: Lint files
        run: npm run lint --prefix remote-frontend/
