
on:
  push:
    branches:
      - master

jobs:

  test-frontend:

    runs-on: ubuntu-16.04
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Generate cache key
        run: echo ${{ hashFiles('**/package-lock.json') }}
      
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
  
        
      - name: Download dependencies
        run: npm i --prefix remote-frontend/
        
      - name: Run tests  
        run: npm test --prefix remote-frontend/
        
      - name: Lint files
        run: npm run lint --prefix remote-frontend/

      - name: build
        run: npm run build --prefix remote-frontend/

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: Remote frontend
          path: |
            ./remote-frontend/build

  test-api:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download deps
        run: go get
      
      - name: Build executable
        run: go build

      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: remote package
          path: |
            ./remote.exe
