
on:
  push:
    branches:
      - master

jobs:

  test:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        
      - name: Download dependencies
        run: npm i
      - run: npm test
      - run: npm lint
